[package]
name = "chershare-factory"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "4.0.0"
serde_json = "1.0.87"
serde = { version = "1", features = ["derive"] }
chershare-resource = { path = "../resource" }
